[package]
name = "tasked"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
better-panic = "0.3.0"
color-eyre = "0.6.3"
directories = "6.0.0"
lazy_static = "1.5.0"
ratatui = "0.29.0"
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.41"
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
